name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint_and_test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [ 1.x ]
        platform: [ ubuntu-latest ]
    name: Lint and Test - ${{ matrix.go-version }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test package
        run: |
            go test -v -race ./...
            go test -v ./... -coverprofile=coverage.txt -covermode count
            go tool cover -func coverage.txt
      - name: Lint package
        uses: golangci/golangci-lint-action@v3
        with:
            version: latest
